### ISSUE TITLE
从standalone到cluster同步时，dbSyncer卡在某个进度一直不动

### ISSUE THREAD

**Issue by oracle1521** [alibaba/RedisShake#114]
### 描述
在使用redis-shake进行从standalone到cluster同步时，dbSyncer卡在某个进度一直不动。

### 相关环境信息
源端type：standalone
redis版本：官方4.0.2

目标端type：3分片cluster
redis版本：4.0.2

redis-shake版本：
improve-1.6.10,cd1ee3561c450e9de0447d20b62115957411d8cd,go1.10.3,2019-07-03_20:11:36
2019/07/04 12:00:10 [WARN] 

### redis-shake配置文件参数
```
id = redis-shake
log.file = ./log/redis-shake.log
log.level = all
pid_path = ./
system_profile = 9310
http_profile = 9320
ncpu = 0
parallel = 32
source.type = standalone
source.address = 
source.password_raw =
source.auth_type = auth
source.tls_enable = false
target.type = cluster
target.address = 
target.password_raw =
target.auth_type = auth
target.db = -1
target.tls_enable = false
rdb.input = local
rdb.output = local_dump
rdb.parallel = 0
rdb.special_cloud = 
fake_time =
rewrite = true
filter.db =
filter.key =
filter.slot =
filter.lua = false
big_key_threshold = 524288000
psync = false
metric = true
metric.print_log = false
heartbeat.url =
heartbeat.interval = 3
heartbeat.external = test external
heartbeat.network_interface =
sender.size = 104857600
sender.count = 5000
sender.delay_channel_size = 65535
keep_alive = 0
scan.key_number = 50
scan.special_cloud =
scan.key_file =
qps = 200000
replace_hash_tag = false
extra = false`
```

### 相关日志
```2019/07/04 11:21:21 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:22 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:23 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:24 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:25 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:26 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:27 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:28 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
2019/07/04 11:21:29 [INFO] dbSyncer[0] total=405032721 -    200684587 [ 49%]  entry=598447
```
从standalone到standalone同步很快就完成了
```2019/07/04 11:32:36 [INFO] dbSyncer[0] total=404794995 -    191318190 [ 47%]  entry=536910
2019/07/04 11:32:37 [INFO] dbSyncer[0] total=404794995 -    194817591 [ 48%]  entry=560165
2019/07/04 11:32:37 [INFO] complete restore big hash key: messageBeenReadKey field:473188
2019/07/04 11:32:37 [INFO] complete restore big hash key: messageBeenReadKey field:473219
2019/07/04 11:32:37 [INFO] complete restore big hash key: messageBeenReadKey field:473223
2019/07/04 11:32:38 [INFO] dbSyncer[0] total=404794995 -    202873434 [ 50%]  entry=614199
2019/07/04 11:32:38 [INFO] complete restore big hash key: messageBeenReadKey field:473224
2019/07/04 11:32:39 [INFO] dbSyncer[0] total=404794995 -    226257082 [ 55%]  entry=758082
2019/07/04 11:32:40 [INFO] dbSyncer[0] total=404794995 -    249263619 [ 61%]  entry=906117
2019/07/04 11:32:41 [INFO] dbSyncer[0] total=404794995 -    272795234 [ 67%]  entry=1048610
2019/07/04 11:32:42 [INFO] dbSyncer[0] total=404794995 -    291275124 [ 71%]  entry=1133506
2019/07/04 11:32:43 [INFO] dbSyncer[0] total=404794995 -    307918209 [ 76%]  entry=1244124
2019/07/04 11:32:44 [INFO] dbSyncer[0] total=404794995 -    327778389 [ 80%]  entry=1372622
2019/07/04 11:32:45 [INFO] dbSyncer[0] total=404794995 -    349499809 [ 86%]  entry=1514138
2019/07/04 11:32:46 [INFO] dbSyncer[0] total=404794995 -    372472834 [ 92%]  entry=1660797
2019/07/04 11:32:47 [INFO] dbSyncer[0] total=404794995 -    395235446 [ 97%]  entry=1807494
2019/07/04 11:32:47 [INFO] dbSyncer[0] total=404794995 -    404794995 [100%]  entry=1872478
2019/07/04 11:32:47 [INFO] dbSyncer[0] sync rdb done
```

**Comment by vinllen** [comment]
打下堆栈发我看下curl http://127.0.0.1:9310/debug/pprof/goroutine?debug=2

**Comment by vinllen** [comment]
表象看堆栈应该是目的端对大key拆分后没有返回，多个都阻塞在这个堆栈上
```
goroutine 45 [chan receive, 4 minutes]:
redis-shake/common.(*ClusterConn).Receive(0xc4235d3440, 0x8524a0, 0xc42375a700, 0x0, 0x0)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/cluster.go:66 +0x53
redis-shake/common.flushAndCheckReply(0x975900, 0xc4235d3440, 0x64)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:337 +0x65
redis-shake/common.restoreBigRdbEntry(0x975900, 0xc4235d3440, 0xc426824000)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:673 +0x6c6
redis-shake/common.RestoreRdbEntry(0x975900, 0xc4235d3440, 0xc426824000)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:758 +0x403
redis-shake.(*dbSyncer).syncRDBFile.func1.1(0xc420d6a030, 0xc420072360, 0x6, 0x6, 0xc420158cb3, 0x4, 0xc420158c20, 0x0, 0x0, 0xc420d6c060, ...)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:441 +0x33a
created by redis-shake.(*dbSyncer).syncRDBFile.func1
        /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:405 +0x131
```
对应代码：
```
// send batcher and put the return into recvChan
func (cc *ClusterConn) Flush() error {
	ret, err := cc.client.RunBatch(cc.batcher)
	cc.batcher = nil // reset batcher
	cc.recvChan <- reply{
		answer: ret,
		err: err,
	}

	return err
}

// read recvChan
func (cc *ClusterConn) Receive() (reply interface{}, err error) {
	ret := <- cc.recvChan
	return ret.answer, ret.err
}
```
cc.recvChan的读取block了，但是Flush发送是有塞入的数据的，不应该会block。
根本原因出在这个函数：
```
func flushAndCheckReply(c redigo.Conn, count int) {
	c.Flush()
	for j := 0; j < count; j++ {
		_, err := c.Receive()
		if err != nil {
			log.PanicError(err, "flush command to redis failed")
		}
	}
}
```
driver限制的问题，对于cluster和standalone的driver处理逻辑不一样，standalone下可以1次Flush多次Receiver，每次读取一条对应的，而cluster是一次Flush只能对应1次Receive，所以后续的就block了。

**Comment by vinllen** [comment]
v1.6.11进行了改进，修改了对redis-go-cluster驱动的适配，1次flush也改为多次receive

**Comment by oracle1521** [comment]
使用新版本后，已成功进行同步，谢谢 @vinllen 的支持~~
