### ISSUE TITLE
不定期全量卡住

### ISSUE THREAD

**Issue by vinllen** [alibaba/RedisShake#119]
源端是2.8.7的redis，同步的时候出现了全量同步到一定比例卡住的现象。每次卡住的比例也不一样，有时候也不卡，顺利进入增量。
tcpdump抓包和redis-shake堆栈都是源端block在发送上，没有继续发送后续的数据。
问题暂时不明，疑似redis本身的问题

**Comment by vinllen** [comment]
堆栈阻塞在读上，也有可能是目的端写入慢了。
```
goroutine 89 [semacquire]:
sync.runtime_notifyListWait(0xc420e866d0, 0xc400003631)
	/data/u4/boyi.gw/tools/go1.10.3/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc420e866c0)
	/data/u4/boyi.gw/tools/go1.10.3/src/sync/cond.go:56 +0x80
pkg/libs/io/pipe.(*pipe).readSome(0xc420164060, 0xc425768000, 0x2000000, 0x2000000, 0x0, 0x0, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/libs/io/pipe/pipe.go:114 +0x201
pkg/libs/io/pipe.(*pipe).Read(0xc420164060, 0xc425768000, 0x2000000, 0x2000000, 0x0, 0x0, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/libs/io/pipe/pipe.go:84 +0x98
pkg/libs/io/pipe.(*reader).Read(0xc420e7e040, 0xc425768000, 0x2000000, 0x2000000, 0x7f06d691cd90, 0x0, 0xc42006f980)
	/home/zhuzhao.cx/redis-shake/src/pkg/libs/io/pipe/pipeio.go:24 +0x4c
bufio.(*Reader).Read(0xc4201640c0, 0xc42b8a8110, 0x89, 0x89, 0x0, 0xc42006f9c0, 0x46f261)
	/data/u4/boyi.gw/tools/go1.10.3/src/bufio/bufio.go:216 +0x238
pkg/libs/stats.(*CountReader).Read(0xc42019a020, 0xc42b8a8110, 0x89, 0x89, 0xc42006fa10, 0x46ec58, 0xc4278de180)
	/home/zhuzhao.cx/redis-shake/src/pkg/libs/stats/iocount.go:33 +0x52
io.(*teeReader).Read(0xc42019a080, 0xc42b8a8110, 0x89, 0x89, 0xc4278de182, 0xc42b8a80d0, 0x40)
	/data/u4/boyi.gw/tools/go1.10.3/src/io/io.go:533 +0x55
pkg/rdb.(*rdbReader).Read(0xc420e7a300, 0xc42b8a8110, 0x89, 0x89, 0x40, 0x0, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:95 +0x55
io.(*teeReader).Read(0xc420172380, 0xc42b8a8110, 0x89, 0x89, 0x40, 0x0, 0x0)
	/data/u4/boyi.gw/tools/go1.10.3/src/io/io.go:533 +0x55
pkg/rdb.(*rdbReader).Read(0xc4295c41e0, 0xc42b8a8110, 0x89, 0x89, 0x40, 0x0, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:95 +0x55
io.ReadAtLeast(0x970980, 0xc4295c41e0, 0xc42b8a80d0, 0xc9, 0xc9, 0xc9, 0x0, 0x7f06d691cd90, 0x0)
	/data/u4/boyi.gw/tools/go1.10.3/src/io/io.go:309 +0x86
io.ReadFull(0x970980, 0xc4295c41e0, 0xc42b8a80d0, 0xc9, 0xc9, 0x85c420, 0x1, 0xc42b8a80d0)
	/data/u4/boyi.gw/tools/go1.10.3/src/io/io.go:327 +0x58
pkg/rdb.(*rdbReader).readFull(0xc4295c41e0, 0xc42b8a80d0, 0xc9, 0xc9, 0xc9, 0xc9)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:417 +0x55
pkg/rdb.(*rdbReader).ReadBytes(0xc4295c41e0, 0xc9, 0x0, 0x0, 0x0, 0xc4209cdc00, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:423 +0x7b
pkg/rdb.(*rdbReader).ReadString(0xc4295c41e0, 0xc4295c41e0, 0xc4278640e0, 0xc42006fdc8, 0x70837a, 0xc420e7a300)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:312 +0x4fa
pkg/rdb.(*rdbReader).readObjectValue(0xc4295c41e0, 0xc427864000, 0xc420e7a2d0, 0x16, 0x0, 0x0, 0x4578b0, 0xc420e7dc80)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/reader.go:127 +0x152
pkg/rdb.(*Loader).NextBinEntry(0xc420e7a2d0, 0xc42006ff80, 0x0, 0x0)
	/home/zhuzhao.cx/redis-shake/src/pkg/rdb/loader.go:202 +0x44a
redis-shake/common.NewRDBLoader.func1(0xc420164120, 0xc4201640c0, 0xc420ec8058)
	/home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:848 +0x23b
created by redis-shake/common.NewRDBLoader
	/home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:841 +0x6d
```
